spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sporttag
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: mypass
    url: jdbc:mariadb://127.0.0.1:3306/sporttag
    username: root
documentservice:
  url: http://localhost:8082/api/v1

environmentname: dev